### ISSUE TITLE
How to integrate with playerjs.com

### ISSUE THREAD

**Issue by tortoros** [Novage/p2p-media-loader#102] opened 2019-10-19 14:14 UTC
We use player https://playerjs.com/en/

How to integrate p2p-media-loader with this player?

**Comment by mrlika** [comment] 2019-10-21 11:16
You can do it like this:
```javascript
function PlayerjsEvents(event,id,data) {
    if (event === "new") {
        window.player.p2pEngine = new p2pml.hlsjs.Engine();

        // store global config
        const config = Hls.DefaultConfig;
        window.player.originalConfig = config;

        // set hls.js config for this instance using global configuration objects
        Hls.DefaultConfig = {
            ...config,
            liveSyncDurationCount: 7,
            loader: window.player.p2pEngine.createLoaderClass()
        };
    } else if (event === "play") {
        const hls = window.player.api("hls");

        if (!hls.p2pInitialized) {
            // initialize hls.js instance
            p2pml.hlsjs.initHlsJsPlayer(hls);
            hls.p2pInitialized = true;
            Hls.DefaultConfig = window.player.originalConfig; // restore global config
        }
    }
}

window.player = new Playerjs({id: "player", file: "https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8"});
```

You have to disable HLS plugin in PlayerJS (to use global hls.js library, not built-in), enable events tracking in PlayerJS and include hls.js script into the page.

**Comment by renatofrota** [comment] 2019-10-21 12:46
Playerjs takes Hls.js config as an object named `hlsconfig` and expose HLS object at `player.api('hls')`, so it's much easier to integrate than above. Works with either integrated (Playerjs' plugin) or external Hls.js.

HTML HEAD
```
<script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-core@latest/build/p2p-media-loader-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-hlsjs@latest/build/p2p-media-loader-hlsjs.min.js"></script>
<script src="https://cdn.plrjs.com/player/YOUR/PLAYERJS.js"></script>
```
(or, as they recommend, download your playerjs' .js file and host it yourself)

If you have disabled the built-in Hls.js plugin in your Playerjs' .js file, load it separately:
```
<script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
```

HTML BODY
```
<div id="player"></div>
```

INLINE JS
```
<script>
var player = new Playerjs({
    id:"player",
    file:"http://EXAMPLE.COM/PLAYLIST.m3u8",
    hlsconfig:{
        liveSyncDurationCount: 7,
        loader = new p2pml.hlsjs.Engine();
    }
});
p2pml.hlsjs.initHlsJsPlayer(player.api('hls'));
</script>
```

**Comment by mrlika** [comment] 2019-10-21 13:39
Nice finding. PlayerJS lacks documentation and no mention in official documentation about this secret `hlsconfig` parameter.

But hlsjs object appears only in the play event of the player and is `undefined` right after player creation. Correct code:

```
function PlayerjsEvents(event,id,data) {
    if (event === "play") {
        const hls = window.player.api("hls");
        if (!hls.p2pInitialized) {
            p2pml.hlsjs.initHlsJsPlayer(hls);
            hls.p2pInitialized = true;

        }
    }
}

const engine = new p2pml.hlsjs.Engine();
window.player = new Playerjs({
    id:"player",
    file:"https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8",
    hlsconfig:{
        liveSyncDurationCount: 7,
        loader: engine.createLoaderClass()
    }
});
```

**Comment by renatofrota** [comment] 2019-10-21 15:12
> Nice finding. PlayerJS lacks documentation and no of this secret `hlsconfig` parameter.
> 
> But `hls.js` instance object appears only in `play` event of the player and is `undefined` right after player creation. Correct code:
> 
> (...)

I have now fixed a typo in my code above (I wrongly wrote `loader =' instead `loader:`) and it is working for me.

Am I missing any feature by using it this way instead binding to the "play" event as in your code?

**Comment by mrlika** [comment] 2019-10-21 22:06
It will not work correctly because `player.api('hls')` returns `undefined`. It will not subscribe to `hls.js` instance events in `initHlsJsPlayer` call.

**Comment by renatofrota** [comment] 2019-10-22 04:01
Even passing an invalid m3u8 URL, `console.log(player.api('hls'));` (right after Playerjs() init) prints a proper Hls.js object instance in my browser console (Firefox and Chrome, latest versions, Linux) - and I have confirmed it is exchanging P2P data (when using a valid m3u8). :yum:

**Comment by mrlika** [comment] 2019-10-22 08:22
I've found out that `hls` is not `undefined` after the player creation ONLY if autoplay is on. That is why my code is more reliable.

By the way this approach (your and mine) doesn't require external hls.js library - you can just enable HLS plugin in PlayerJS and it will use built in one.

**Comment by mrlika** [comment] 2019-10-22 08:51
And new finding - when autoplay is on it doesn't fire `play` event at all. So @renatofrota code works for autoplay and my code works without autoplay. Strange player...

**Comment by denisstepkin** [comment] 2019-10-22 20:06
You can simply disable HLS plugin in the builder and use custom build without request of this object. The "play" event always fires.

**Closed** 2019-10-29 12:24 UTC

**Comment by marcoscv1981** [comment] 2021-08-24 20:18
Someone managed to make it work, here it opens normal the player works, but P2P does not work. What can it be ?

**Comment by marksjr** [comment] 2022-09-29 05:08
Any solution for the current version?

> Does it working with current playerjs for anyone?

Any solution for the current version?
