### ISSUE TITLE
Video Stuck at Error

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#58] opened 2019-03-24 19:00 UTC
Hello,

I'm having an issue with the new version of script. Sometimes with media load error or some other reasons with http video stuck with loading. 

```
loader: {
		cachedSegmentExpiration: 1000*60*60*2,
		cachedSegmentsCount: 800,
		simultaneousHttpDownloads: 2,
		simultaneousP2PDownloads: 15,
		httpFailedSegmentTimeout: 2000,
		p2pSegmentDownloadTimeout: 5000,
		httpDownloadProbabilitySkipIfNoPeers: true
	},
```

![image](https://user-images.githubusercontent.com/9140369/54884270-ef0e0f80-4e7f-11e9-8b20-691d9f34e55b.png)

Is it because of my config or some kind of bug?

**Comment by mrlika** [comment] 2019-03-25 08:56
Hi,

Is there any URL that reproduces the issue?

**Comment by nickcartery** [comment] 2019-03-27 03:28
I had the same issue :)) It's caused by timeout in xhrSetup :)

Try this:

```
    var p2p_settings = {
        loader: {
            trackerAnnounce: ["wss://tracker.fastcast.nz"],
            xhrSetup: function(xhr, url) {
                xhr.timeout = 10000; // max timeout = 10s
                xhr.ontimeout = function(e){
                    var parsedUrl = new URL(url);
                    var retry_time = parsedUrl.searchParams.get("retry_time");

                    if(retry_time)
                        retry_time = 1 + parseInt(retry_time);
                    else
                        retry_time = 1;

                    //renew load HLS if cannot retry after 5 times
                    if(retry_time > 5)
                        loadHLSPlayer(stream);

                    parsedUrl.searchParams.set("retry_time", retry_time);
                    url = url.href;

                    xhr.open('GET', url, true);
                    xhr.send();
                }
                // console.log(xhr);
                // xhr.withCredentials = true; // do send cookies
            }
        }
    }
```

**Comment by mrlika** [comment] 2019-03-27 11:59
You shouldn't retry. It is done by the library. `xhrSetup` is mostly to configure headers of XHR request in case of media stream protection like DRM: [httpFailedSegmentTimeout](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loader--new-hybridloadersettings)

**Comment by mrlika** [comment] 2019-03-27 12:13
And yes, you are right. It hangs if a `xhr.timout` is set in `xhrSetup`.

Fixed in 626b59415d4bb25738e3a61f6a5e689a5b31d21d.

**Comment by defrinex** [comment] 2019-04-04 19:33
> And yes, you are right. It hangs if a `xhr.timout` is set in `xhrSetup`.
> 
> Fixed in [626b594](https://github.com/Novage/p2p-media-loader/commit/626b59415d4bb25738e3a61f6a5e689a5b31d21d).

Hello

It seems like my timeout problem is caused from hlsjs not the core. Could you please check this out?

![1](https://user-images.githubusercontent.com/9140369/55582897-3f5f5a00-5729-11e9-98cc-6e5593b41785.png)
![2](https://user-images.githubusercontent.com/9140369/55582848-26ef3f80-5729-11e9-816a-4cd003c73c91.png)

**Comment by mrlika** [comment] 2019-04-05 09:52
It is a network error. HTTP request fails. Network errors may cause a video to stuck.

I will check if some kind of network errors resistance can be added there.

**Comment by defrinex** [comment] 2019-04-08 13:07
It would be great at least some error shows up on the frond-end. Because when this error occurs, end user dont see any error and it looks like video still loading.

**Comment by mrlika** [comment] 2019-04-10 07:29
> I'm having an issue with the new version of script. Sometimes with media load error or some other reasons with http video stuck with loading.

Does it happen when you start playback or while playback?

What player are you using? For example, Clappr handles Hls.js errors and shows an error message at the beginning. Hls.js player itself doesn't show any message and looks like stuck.

**Comment by defrinex** [comment] 2019-04-10 13:48
> > I'm having an issue with the new version of script. Sometimes with media load error or some other reasons with http video stuck with loading.
> 
> Does it happen when you start playback or while playback?
> 
> What player are you using? For example, Clappr handles Hls.js errors and shows an error message at the beginning. Hls.js player itself doesn't show any message and looks like stuck.

I'm using videojs player. It sometimes stuck at the beginning. And sometimes middle of the video.

**Comment by defrinex** [comment] 2019-04-10 18:14
Looks like increasing the httpFailedSegmentTimeout value solved the issue for temporary. But It will still be a problem if the master.m3u8 wont load before the timeout. I see that there is no then&catch method on loadPlaylist like loadSegment. I tried to add one but the xhr.send() line throws an javascript error. I couldn't bypass it.

![image](https://user-images.githubusercontent.com/9140369/55902796-f3069500-5bd4-11e9-9aa2-895a13e0d826.png)

**Comment by defrinex** [comment] 2019-04-10 19:28
I see that then&catch is defined where the loadPlaylist called.

![image](https://user-images.githubusercontent.com/9140369/55907354-36fe9780-5bdf-11e9-8551-93cccdfd9481.png)


So I added the code below in loadContent xhr and expect player to give me an error when master.m3u8 timed out. I got the console log but the catch function at the screenshot above not worked and no error occurred;

```
xhr.addEventListener("error", () => {
	console.log("Network Error");
	reject("Network Error");
});
```

![image](https://user-images.githubusercontent.com/9140369/55907549-be4c0b00-5bdf-11e9-90b8-b7d797feaf09.png)

**Comment by mrlika** [comment] 2019-04-12 00:20
I can't reproduce the behaviour. Playlist load error events are passed to hls.js engine and it is up to the engine how to process them.

> So I added the code below in loadContent xhr and expect player to give me an error when master.m3u8 timed out. I got the console log but the catch function at the screenshot above not worked and no error occurred;

In your example `error` event handler will not trigger `catch` function by calling `reject` because `catch` function is triggered in `readystatechange` handler that calls `reject` earlier.

ERR_CONNECTION_TIMED_OUT changes ready state of the xhr object thus it should be processed in `readystatechange` event handler and call `reject`.

**Comment by mrlika** [comment] 2019-04-12 00:32
Looks like it is problem with video.js (and videojs-contrib-hlsjs plugin) that it keeps showing loading process while a network error inside hls.js engine. For example, Clappr processes the errors and displays corresponding error message.

> So I added the code below in loadContent xhr and expect player to give me an error when master.m3u8 timed out. I got the console log but the catch function at the screenshot above not worked and no error occurred;

In your example `error` event handler will not trigger `catch` function by calling `reject` because `catch` function is triggered in `readystatechange` handler that calls `reject` earlier.

**Closed** 2019-04-18 08:32 UTC

**Comment by defrinex** [comment] 2019-04-22 14:40
> Looks like it is problem with video.js (and videojs-contrib-hlsjs plugin) that keeps showing loading process while a network error inside hls.js engine. For example, Clappr processes the errors and displays corresponding error message.
> 
> >

Do you have any solution for this? Like writing a custom function or anything like that? I just need to know how to catch this issue.

**Comment by mrlika** [comment] 2019-04-22 19:32
No solution. It looks like the issue in videojs-contrib-hlsjs plugin.
